import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/shared/lib";
import { mulish } from "./fonts";
import { AppProvider } from "@/shared/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={cn(mulish.variable, "min-h-screen antialiased")}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}

